MINJOO-KIM/Movie

backend/movie_recommend/settings.py
다른 PC 환경에는 TMDB TOKEN 을 담은 .env 파일이 존재하지 않아 실행에 문제가 있었습니다.
데이터 수집을 완료하였으므로 더 이상 필요치 않은 코드를 주석처리 하였습니다.
=> fix : 데이터 수집을 위한 TMDB TOKEN 설정 주석 처리하여 다른 PC 환경에서 실행 오류 발생하는 문제 해결

backend/movie_recommend/settings.py, backend/movie_recommend/urls.py, backend/movies/serializers.py, backend/movies/urls.py, backend/movies/views.py, backend/requirements.txt
> 설문에 필요한 장르 목록을 조회할 수 있는 기능을 개발했습니다.
> 설문 결과가 영화 추천에 불충분할 경우 필요한 랜덤 추천 기능을 개발했습니다.
=> feat : 장르 목록 조회 기능, 영화 랜덤 추천 기능, 영화 상세 정보 조회 기능 개발

README.md, backend/movie_recommend/settings.py, backend/requirements.txt
> CORS 에러를 해결했습니다. 다만 임시적으로 테스트를 위한 목적이므로 모든 ORIGIN 에 대해 허용하도록 했습니다.
=> fix : CORS 에러 해결

frontend/movie-recommend/src/components/movies/MovieDetailInfo.vue, frontend/movie-recommend/src/views/MovieDetailView.vue
> 영화 상세 페이지 CSS 작업했습니다. 스타일링 과정에서 html 태그들의 클래스 명 등에는 약간의 조정이 있습니다.
=> style : 영화 상세 페이지 css 스타일 적용

frontend/movie-recommend/src/App.vue
> 배경 이미지 src 가 절대경로로 되어있어 코드를 작성했던 PC 외에는 경로가 올바르지 않는 문제가 있었습니다. 상대 경로를 사용하도록 하여 문제를 해결했습니다.
=> fix :배경 이미지  절대 경로를 상대 경로로 변경

backend/movies/views.py
> 영화 상세 정보 조회 API 가 평점을 소수점 아래 한 자리까지만 출력하도록 수정했습니다.
=> feat : 영화 상세페이지 조회 시 평점 소수점 한 자리까지 출력

frontend/movie-recommend/src/router/index.js, frontend/movie-recommend/src/views/LoginView.vue, frontend/movie-recommend/src/views/SignupView.vue
> 회원가입 페이지 뷰 생성 및 라우터 등록 후 CSS 작업했습니다.
=> style : signup view 생성 및 css 적용

frontend/movie-recommend/src/router/index.js, frontend/movie-recommend/src/views/LoginView.vue
> 로그인 페이지 뷰 생성 및 라우터 등록 후 CSS 작업했습니다
=> style : LoginView 생성 및 css 적용

frontend/movie-recommend/src/App.vue, frontend/movie-recommend/src/components/common/OTTNavbar.vue, frontend/movie-recommend/src/views/HomeView.vue, frontend/movie-recommend/src/views/MyPageView.vue
> OTT 서비스 navbar 구성을 기획에 맞게 변경했습니다.
> route name 에 따라 navbar 가 다르게 보이도록 했습니다.
=> style : ott 서비스 navbar 제작

frontend/movie-recommend/src/components/otts/PartyCard.vue, frontend/movie-recommend/src/views/PartyCreateView.vue, frontend/movie-recommend/src/views/PartyJoinView.vue
> 파티 참여 기능을 구현했습니다.
- PartyJoinView
- PartyCard
=> feat: 파티 참여 기능 구현

frontend/movie-recommend/src/views/PartyCreateView.vue
> 파티 생성 페이지 CSS 작업했습니다.
> input type=number 인 요소들의 경우 기본 제공되는 컨트롤바로 인해 디자인에 어려움이 있어 text 로 변경했습니다.
=> style : 파티 생성 페이지 CSS 작업

frontend/movie-recommend/src/components/movies/Recommend.vue
> 취항 설문 페이지 input 박스 outline 제거 했습니다.
=> style : 취향 설문 input 박스 outline 제거

frontend/movie-recommend/src/components/otts/MyPartyCard.vue, frontend/movie-recommend/src/components/otts/MyPartyCreated.vue, frontend/movie-recommend/src/components/otts/MyPartyJoined.vue, frontend/movie-recommend/src/stores/movie.js
> 마이페이지 기능을 구현하였습니다.
- 내가 만든 파티
- 내가 참여중인 파티
- 파티 계정 정보 수정하기
- 파티 탈퇴하기
=> feat: 마이페이지 기능 구현

frontend/movie-recommend/src/components/otts/PartyCard.vue, frontend/movie-recommend/src/views/PartyJoinView.vue
> 파티 목록 조회 및 참여하기가 가능한 페이지 CSS 작업했습니다.
=> style : 파티 참여하기 페이지 css 작업

frontend/movie-recommend/src/components/movies/MovieDetailInfo.vue, frontend/movie-recommend/src/views/OTTHomeView.vue
> OTT 서비스 메인 페이지 버튼 여백 조정 및 소개 텍스트 수정
=> style : OTT 공유 서비스 메인 페이지 수정

frontend/movie-recommend/src/components/movies/MovieRecommend.vue
> 영화 추천 재요청, 취향 재작성 버튼 hover 시 CSS 수정
=> style : 영화 추천 페이지 버튼 css 수정

frontend/movie-recommend/src/components/movies/MovieDetailInfo.vue
> 영화 상세페이지 좌우 여백 수정 및 스크롤 적용했습니다. 내부 버튼 CSS 수정했습니다.
=> style : 영화 상세페이지 CSS 수정

frontend/movie-recommend/src/components/otts/MyPartyCard.vue, frontend/movie-recommend/src/components/otts/MyPartyJoined.vue
=> style : 마이페이지 스크롤바 수정

frontend/movie-recommend/src/views/PartyCreateView.vue
> 새로운 파티 만들기 카드 위 아래쪽 여백을 수정하여 카드가 화면의 중앙에 위치할 수 있도록 했습니다.
=> style : 위 아래 여백 조정

backend/data_crawler.py, frontend/movie-recommend/src/components/movies/MovieCard.vue, frontend/movie-recommend/src/components/movies/MovieDetailInfo.vue, frontend/movie-recommend/src/components/movies/MovieRecommend.vue, frontend/movie-recommend/src/components/movies/Recommend.vue, frontend/movie-recommend/src/router/index.js, frontend/movie-recommend/src/stores/movie.js, frontend/movie-recommend/src/views/HomeView.vue
> 영화 취향 페이지를 입력하기 전이면 취향페이지를 통해 취향을 입력한 후, 추천 영화를 보여줄 수 있도록 구현하였습니다.
=> feat: 영화 추천페이지 UI 분기 처리 및 axios 요청 분리

frontend/movie-recommend/src/App.vue
> router name 변경에 맞춰 App.vue 에서도 분기처리하는 router name 을 수정했습니다.
=> fix : router name 변경에 따라 App.vue 수정

backend/movies/functions.py
> 영화 추천 시 (선호 장르, 선호 배우) 조합을 활용할 수 있도록 개선했습니다.
=> feat : 영화 추천 시 장르, 배우 조합 정보 활용하도록 개선

backend/movies/functions.py
> 영화 추천 시 선택 입력 파라미터인 recommended 가 "" 을 허용할 수 있도록 수정
=> fix : 영화 추천 시 recommended 파라미터에 공백 들어올 때 정상 동작하도록 수정

frontend/movie-recommend/src/components/movies/MovieRecommend.vue, frontend/movie-recommend/src/components/movies/Recommend.vue, frontend/movie-recommend/src/stores/movie.js, frontend/movie-recommend/src/views/HomeView.vue
> 영화 추천 페이지 (추천 영화 새로고침 요청 / 취향 재입력) 버튼 기능 구현하였습니다.
=> feat: 영화 추천페이지 - 새로운 영화 추천, 취향 다시 입력하는 기능 구현

backend/accounts/views.py, frontend/movie-recommend/src/components/common/OTTNavbar.vue, frontend/movie-recommend/src/components/movies/MovieRecommend.vue, frontend/movie-recommend/src/components/otts/MyPartyCreated.vue, frontend/movie-recommend/src/components/otts/MyPartyJoined.vue, frontend/movie-recommend/src/components/otts/PartyCard.vue, frontend/movie-recommend/src/router/index.js, frontend/movie-recommend/src/stores/movie.js, frontend/movie-recommend/src/views/LoginView.vue, frontend/movie-recommend/src/views/PartyCreateView.vue, frontend/movie-recommend/src/views/SignupView.vue
> 마이페이지 회원가입, 로그인, 로그아웃, 인증여부에 따른 분기 처리를 구현하였습니다.
=> feat: 마이페이지 인증 기능 구현

backend/movie_recommend/settings.py
> cors allow origin 을 localhost 만 되도록 수정했습니다.
=> fix : cors allow origin 수정

frontend/movie-recommend/src/stores/movie.js
> 회원가입 후 자동로그인 처리 및 홈화면으로 이동하는 기능을 구현하였습니다.
=> fix: 회원가입 후 자동 로그인 처리

frontend/movie-recommend/src/views/PartyCreateView.vue
> 파티 생성하기 필수 입력 값 기능을 추가하였습니다.
=> feat: 파티 생성하기 필수 입력 값 기능 구현

frontend/movie-recommend/src/components/otts/MyPartyCreated.vue, frontend/movie-recommend/src/components/otts/MyPartyJoined.vue, frontend/movie-recommend/src/components/otts/PartyCard.vue, frontend/movie-recommend/src/stores/movie.js, frontend/movie-recommend/src/views/MovieDetailView.vue
> axios 에러 발생 시 단순 console.log 만 하지 않고 alert 창으로 유저에게 알림 후 적절한 페이지로 이동하는 로직 추가
=> fix : axios 에러 발생 시 alert 및 라우팅 로직
